driver:
  name: ec2
  aws_ssh_key_id: sydney-work
  region: ap-southeast-2
  availability_zone: ap-southeast-2a
  require_chef_omnibus: true
  instance_type: t2.large
  iam_profile_name: Elmo-Sydney-ELK
  subnet_id: subnet-53c2b637
  associate_public_ip: true
  shared_credentials_profile: default
  security_group_ids: ["subnet-53c2b637"]
  tags:
    Name: "test-ELK"

transport:
  ssh_key: /Users/anuragmathur/Documents/AWS/KeyPair/sydney-work.pem
  username: ec2-user

provisioner:
  name: chef_solo

platforms:
  - name: amazon
    driver:
      image_id: ami-8bf2fde8
      transport.username: ec2-user

suites:
  - name: default
    run_list:
      - recipe[elk::default]

    attributes:
        general:
            #api_domain: core.elmodev.com
            timezone: Australia/Sydney
